 
service: authorization-service


frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true


functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
    events:
      - http:
          path: products
          method: get
          cors: true